apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
  labels:
        app: {{ .Values.app_name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
        version: {{ .Values.labels.version }}
        version2: {{ .Values.labels.version2 }}