---
# Source: s3/templates/deploy-espresso_shop_product_catalog.yml
# Source: espresso-shop-product-catalog/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: espresso-shop-product-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: espresso-shop-product-catalog
  template:
    metadata:
      labels:
        app: espresso-shop-product-catalog
        version: v1
    spec:
      containers:
        - name: espresso-shop-product-catalog
          image: "devopseasylearning2021/s3-project01-espresso-shop-product:v1.0.0"
          imagePullPolicy: Always
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_HOST
              value: espresso-shop-postgres
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi