

---
# Source: s3/templates/pvc-postgres-replication.yml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-replication-pv-claim 
  labels:
    app: espresso-shop-reviews
spec:
  storageClassName: do-block-storage-retain
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 3Gi


---
# Source: s3/templates/pvc-postgres.yml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim   
  labels:
    app: espresso-shop-reviews
spec:
  storageClassName: do-block-storage-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi