


---
# Source: s3/templates/service-espresso_shop_product_catalog.yml
apiVersion: v1
kind: Service
metadata:
  name: espresso-shop-product-catalog-svc
  labels:
    app: espresso-shop-product-catalog
spec:
  type: ClusterIP
  ports:
    - port: 8091
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: espresso-shop-product-catalog


---
# Source: s3/templates/service-espresso_shop_reviews.yml
apiVersion: v1
kind: Service
metadata:
  name: espresso-shop-reviews-svc
  labels:
    app: espresso-shop-reviews
    version: v1
    version: v2
spec:
  type: ClusterIP
  ports:
    - port: 8092
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: espresso-shop-reviews


---
# Source: s3/templates/service-espresso_shop_web.yml
apiVersion: v1
kind: Service
metadata:
  name: espresso-shop-web-svc
  labels:
    app: espresso-shop-web
spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: espresso-shop-web


---
# Source: s3/templates/service-postgres-replication.yml
apiVersion: v1
kind: Service
metadata:
  name: postgres-replication
  labels:
    app: espresso-shop-reviews
spec:
  type: ClusterIP 
  ports:
    - port: 5432 
  selector:
    app: espresso-shop-reviews


---
# Source: s3/templates/service-postgres.yml
apiVersion: v1
kind: Service
metadata:
  name: postgres 
  labels:
    app: espresso-shop-reviews
spec:
  type: ClusterIP 
  ports:
    - port: 5432 
  selector:
    app: espresso-shop-reviews


---
# Source: s3/templates/service-redis.yml
apiVersion: v1
kind: Service                    
metadata:
  name: espresso-shop-redis 
  labels:
    app: espresso-shop-web
spec:
  type: NodePort             
  ports:                         
  - name: http
    port: 9090
    targetPort: 8080
  selector:
    app: espresso-shop-web

    